Repository GSG-G4/gsg-for-better, pull requests merged in 2018-12, with the labels that each got.

#49 Continuous Integaration
  .travisl.yml
Labels: approved

#53 refactor: fixes mongouri environment variable name
  server/database/config.js
Labels: awaiting-review

#50 Deploy initial setup on heroku
  package-lock.json
  package.json
  server/app.js
Labels: awaiting-review

#78 Fix react dirname in express server.
  package-lock.json
  package.json
  server/app.js
Labels: awaiting-review

#80 Edit technology schema
  server/database/models/technology.js
Labels: approved

#85 Fix the bug build fake data
  server/database/fake_data/index.js
Labels: awaiting-review

#86 Add user fake data
  server/__test__/schema/user.js
  server/database/fake_data/delete_fake_data.js
  server/database/fake_data/index.js
  server/database/fake_data/user.js
Labels: approved

#88 Goal and Progress fake data.
  server/__test__/schema/goal.test.js
  server/__test__/schema/progress.test.js
  server/database/fake_data/delete_fake_data.js
  server/database/fake_data/goal.js
  server/database/fake_data/index.js
  server/database/fake_data/progress.js
Labels: awaiting-review

#92 Project fake data
  server/__test__/schema/progress.test.js
  server/__test__/schema/project.test.js
  server/database/fake_data/delete_fake_data.js
  server/database/fake_data/index.js
  server/database/fake_data/progress.js
  server/database/fake_data/project.js
Labels: awaiting-review

#93 [fix] fixes typo in team data file
  server/database/fake_data/team.js
Labels: awaiting-review, bug

#99 Timeline fake data
  server/__test__/schema/timeline.test.js
  server/database/fake_data/delete_fake_data.js
  server/database/fake_data/index.js
  server/database/fake_data/timeline.js
Labels: awaiting-review

#97 Staged actions
  server/__test__/schema/staged_action.test.js
  server/database/fake_data/delete_fake_data.js
  server/database/fake_data/index.js
  server/database/fake_data/staged_action.js
Labels: awaiting-review

#104 Landing page wrapper
  client/src/App.js
  client/src/components/Footer/index.js
  client/src/components/Header/index.js
  client/src/components/LandingPage/Community/index.js
  client/src/components/LandingPage/ProjectsSection/index.js
  client/src/components/LandingPage/Team/index.js
  client/src/components/LandingPage/TechStack/index.js
  client/src/components/LandingPage/Timeline/index.js
  client/src/components/LandingPage/index.js
Labels: approved

#107 Add user specialty
  server/database/fake_data/user.js
  server/database/models/user.js
Labels: awaiting-review
